name: Bench CI
on:
  push:
    paths: ['bench/**']
  pull_request:
    paths: ['bench/**']
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: taiki-e/install-action@just
      - name: Build
        run: cd bench && just build
      - name: Test
        run: cd bench && just test
