name: Docs CI
on:
  push:
    paths: ['docs/**']
  pull_request:
    paths: ['docs/**']
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: taiki-e/install-action@just
      - name: Build
        run: cd docs && just build
      - name: Test
        run: cd docs && just test
