name: ML CI
on:
  push:
    paths: ['ml/**']
  pull_request:
    paths: ['ml/**']
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: taiki-e/install-action@just
      - name: Build
        run: cd ml && just build
      - name: Test
        run: cd ml && just test
